export const TaskData = [


    {
        id: 1,
        taskName: 'Task Item',
        description: 'Task Item Description',
        due_date: '2022-08-01',
        listName: 'Purchase',
        assigned_to: 'Bob Buyer',
        completed: false,
    },
    {
        id: 2,
        taskName: 'Task Item 2',
        description: 'Task Item Description 2',
        due_date: '2022-08-02',
        listName: 'Pre-sale',
        assigned_to: 'Ally Agent',
        completed: true,
    },
    {
        id: 3,
        taskName: 'Task Item 3',
        description: 'Task Item Description 3',
        due_date: '2022-08-03',
        listName: 'Pre-sale',
        assigned_to: 'Bob Buyer',
        completed: false,
    },
    {
        id: 4,
        taskName: 'Task Item 4',
        description: 'Task Item Description 4',
        due_date: '2022-08-04',
        listName: 'Purchase',
        assigned_to: 'Ally Agent',
        completed: false,
    },
    {
        id: 5,
        taskName: 'Task Item 5',
        description: 'Task Item Description 5',
        due_date: '2022-08-05',
        listName: 'Financing',
        assigned_to: 'Bob Buyer',
        completed: false,
    },
    {
        id: 6,
        taskName: 'Task Item 6',
        description: 'Task Item Description 6',
        due_date: '2022-08-06',
        listName: 'Pre-sale',
        assigned_to: 'Ally Agent',
        completed: true,
    },
    {
        id: 7,
        taskName: 'Task Item 7',
        description: 'Task Item Description 7',
        due_date: '2022-09-01',
        listName: 'Pre-sale',
        assigned_to: 'Bob Buyer',
        completed: false,
    },
]

